env:
  browser: true
  es2021: true
  jest: true
extends:
  - plugin:react/recommended
  - plugin:testing-library/react
  - airbnb
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - testing-library
  - react
  - react-hooks
  - '@typescript-eslint'
  - prettier
rules:
  react/jsx-filename-extension: off
  import/no-unresolved: off
  import/extensions: off
  no-plusplus: off

settings:
  import/resolver: webpack

